{% set name = "colcon-core" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 005e5c3260e03c3118fe96a12b08e443947382fd376a97389c630064c1a6b5fc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - colcon = colcon_core.command:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - coloredlogs
    - distlib
    - empy
    - pytest
    - pytest-cov
    - pytest-repeat
    - pytest-rerunfailures
    - setuptools >=30.3.0

test:
  imports:
    - colcon
    - colcon_core
  commands:
    - pip check
    - colcon --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    colcon is a command line tool to improve the workflow of building,
    testing and using multiple software packages.

extra:
  recipe-maintainers:
    - j-rivero
    - traversaro
    - seanyen
    - wolfv
