{% set name = "colcon-core" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3ed2738aff9e7c01efbbd62310cde2c0c65920058344729ebe4ac7d34a8ec806

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35]
  entry_points:
    - colcon = colcon_core.command:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - coloredlogs  # [win]
    - distlib
    - EmPy
    - pytest
    - pytest-cov
    - pytest-repeat
    - pytest-rerunfailures
    - pytest-runner
    - setuptools >=30.3.0

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    colcon is a command line tool to improve the workflow of building,
    testing and using multiple software packages.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
