context:
  name: colcon-core
  version: "0.20.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/colcon/${{ name }}/archive/${{ version }}.tar.gz
  sha256: 1e4047c0fb3f9e3a582ff190846843f8dedaa9e314ff93cdb4784daaaf99ac27

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv
  noarch: python
  python:
    entry_points:
      - colcon = colcon_core.command:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - coloredlogs
    - distlib
    - empy
    - pytest
    - pytest-cov
    - pytest-repeat
    - pytest-rerunfailures
    - setuptools >=30.3.0

tests:
  - python:
      imports:
        - colcon
        - colcon_core
      python_version: ${{ python_min }}.*
  - script:
      - colcon --help

about:
  homepage: https://github.com/colcon/${{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    colcon is a command line tool to improve the workflow of building,
    testing and using multiple software packages.
  repository: https://github.com/colcon/${{ name }}
  documentation: https://colcon.readthedocs.io/en/released/

extra:
  recipe-maintainers:
    - j-rivero
    - traversaro
    - seanyen
    - wolfv
